name: Daily ArcGIS Layer Update

on:
  schedule:
    #- cron: '0 0 * * *'
  workflow_dispatch:

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout code
        uses: actions/checkout@v3

      - name: Setup Conda
        uses: conda-incubator/setup-miniconda@v2
        with:
          auto-update-conda: true
          python-version: '3.9' # Consistent version
          channels: esri,conda-forge
          channel-priority: true

      - name: Install ArcGIS via Conda
        shell: bash -l {0}
        run: |
          conda install arcgis requests -y

      - name: Run Update Script
        shell: bash -l {0}
        env:
          ARCGIS_CLIENT_ID: ${{ secrets.ARCGIS_CLIENT_ID }}
          ARCGIS_CLIENT_SECRET: ${{ secrets.ARCGIS_CLIENT_SECRET }}
        run: python update_script.py
